#
# Module manifest for module 'k8s.Selenium'
#
# Generated by: Amit Kshirsagar
#
# Generated on: 3/20/2020
#

@{

  # Script module or binary module file associated with this manifest.
  RootModule = 'k8s.Selenium.psm1'
  
  # Version number of this module.
  ModuleVersion = '1.0.1'
  
  # Supported PSEditions
  CompatiblePSEditions = 'Core', 'Desktop'
  
  # Author of this module
  Author = 'Amit Kshirsagar'
  
  # Company or vendor of this module
  CompanyName = 'AMN'
  
  # Copyright statement for this module
  Copyright = 'AMN.'
  
  # Description of the functionality provided by this module
  Description = 'Run JMeter with Powershell and extract reports.
  '
  
  # Minimum version of the PowerShell engine required by this module
  PowerShellVersion = '5.1'
  DotNetFrameworkVersion = '4.7.2'
  RequiredModules = @()
  FunctionsToExport = @("Get-TestMessage","Get-SEChrome","Test-SeleniumLogin","Test-RestCall")
  # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
  CmdletsToExport = @()
  # Variables to export from this module
  # VariablesToExport = @()
  # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
  AliasesToExport = @()
}